version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django06g8e
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=django06g8e
      - SITE_DOMAIN=craftmarket.com
    volumes:
      - media_data:/app/media
      - static_data:/app/static
      - ./templates:/app/templates
    entrypoint: ["/app/entrypoint.sh"]
    command: ["sh", "-c", "python docker_image_fix.sh && python manage.py runserver 0.0.0.0:8080"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/var/www/media
      - static_data:/var/www/static
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  media_data:
  static_data: 