version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: django06g8e
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  web:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=django06g8e
      - SITE_DOMAIN=${SITE_DOMAIN:-localhost}
      - PORT=8080
    volumes:
      - ./media:/app/media
      - ./templates:/app/templates
    command: >
      sh -c "python collections_patch.py &&
             python docker_image_fix.sh &&
             python manage.py runserver 0.0.0.0:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 